---
title: "R Notebook"
output:
  html_document:
    df_print: paged
---


```{r}
source("C:/Users/User/Desktop/rgz/Classification/src/sampleGeneration.R")
source("C:/Users/User/Desktop/rgz/Classification/src/classification.R")
```


```{r}
mainFunc <- function(ntrain=1000, m11=1, m21=5, sd11=1, sd21=1, p1=0.5) {
  ntest <- floor(0.25*ntrain)
  p2 <- 1 - p1
  m12 <- 1
  m22 <- 3
  sd12 <- 1
  sd22 <- 1
  k <- 100
  typeGener <- "Central limit theorem"
  
  sample <- sampleGeneration(typeGener, ntrain, ntest, m11, m12, sd11, sd12, m21, m22, sd21, sd22, k, p1)
  x1train <- sample$x1train
  x2train <- sample$x2train
  n1train <- sample$n1train
  n2train <- sample$n2train
  
  x1test <- sample$x1test
  x2test <- sample$x2test
  n1test <- sample$n1test
  n2test <- sample$n2test
  
  m11est <- mean(x1train[,1])
  m12est <- mean(x1train[,2])
  sd11est <- (sd(x1train[,1]))^2
  sd12est <- (sd(x1train[,2]))^2
  m21est <- mean(x2train[,1])
  m22est <- mean(x2train[,2])
  sd21est <- (sd(x2train[,1]))^2
  sd22est <- (sd(x2train[,2]))^2
  p1est <- n1train/ntrain
  p2est <- n2train/ntrain
  x <- c(x1train[,1], x2train[,1])
  y <- c(x1train[,2], x2train[,2])
  sd1est <- sd(x)
  sd2est <- sd(y)
  
  points <- classification(n1test, n2test, x1test, x2test, sd1est, sd2est,
                         m11est, m12est, m21est, m22est, p1est, p2est)
}
```

```{r}
wrapper_n <- function(n) {
  mainFunc(ntrain = n)$err
}

wrapper_m21_m11 <- function(m21) {
  mainFunc(m21 = m21)$err
}

wrapper_sd11_sd21_s <- function(sd21) {
  mainFunc(sd21 = sd21, m11 = 1, m21 = 1)$err
}

wrapper_sd11_sd21_d <- function(sd21) {
  mainFunc(sd21 = sd21, m11 = 1, m21 = 4)$err
}

wrapper_p1_s <- function(p1) {
  mainFunc(p1 = p1, m11 = 1, m21 = 1)$err
}

wrapper_p1_d <- function(p1) {
  mainFunc(p1 = p1, m11 = 1, m21 = 4)$err
}
```

```{r}
depend_P_N <- function() {
  arrN <- c(100, 300, 500, 1000, 2000, 3000, 4000, 5000)
  arrP <- Vectorize(wrapper_n)(arrN)
  plot(arrN, arrP, main="Зависимость ошибки от объема выборки", xlab="N", ylab="P", type = "l",
       col = "red")
}

depend_P_m21_m11 <- function() {
  m11 <- 1
  arrM21 <- c(2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12)
  arrSubM <- arrM21 - m11
  arrP <- Vectorize(wrapper_m21_m11)(arrM21)
  plot(arrSubM, arrP, main="Зависимость ошибки от разности мат. ожиданий", 
       xlab="Разность мат. ожиданий", ylab="P", type = "l", col = "blue")
}

depend_P_sd11_sd21_s <- function() {
  sd11 <- 1
  arrSD21 <- c(1, 3, 5, 7, 10, 13, 15, 17, 20)
  arrSubSD <- arrSD21^2 - sd11^1
  arrP <- Vectorize(wrapper_sd11_sd21_s)(arrSD21)
  plot(arrSubSD, arrP, main="Зависимость ошибки от разности дисперсий (одинаковые мат. ожид.)", 
       xlab="Разность дисперсий", ylab="P", type = "l", col = "yellow")
}

depend_P_sd11_sd21_d <- function() {
  sd11 <- 1
  arrSD21 <- c(1, 3, 5, 7, 10, 13, 15, 17, 20)
  arrSubSD <- arrSD21^2 - sd11^1
  arrP <- Vectorize(wrapper_sd11_sd21_d)(arrSD21)
  plot(arrSubSD, arrP, main="Зависимость ошибки от разности дисперсий (разные мат. ожид.)", 
       xlab="Разность дисперсий", ylab="P", type = "l", col = "yellow")
}

depend_P_p1_s <- function() {
  arrp1 <- c(0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.7, 0.9)
  arrP <- Vectorize(wrapper_p1_s)(arrp1)
  plot(arrp1, arrP, main="Зависимость ошибки от p1 (одинаковые мат. ожид.)", 
       xlab="p1", ylab="P", type = "l", col = "green")
}

depend_P_p1_d <- function() {
  arrp1 <- c(0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.7, 0.9)
  arrP <- Vectorize(wrapper_p1_d)(arrp1)
  plot(arrp1, arrP, main="Зависимость ошибки от p1 (разные мат. ожид.)", 
       xlab="p1", ylab="P", type = "l", col = "green")
}
```

```{r}
depend_P_N()
depend_P_m21_m11()
depend_P_sd11_sd21_s()
depend_P_sd11_sd21_d()
depend_P_p1_s()
depend_P_p1_d()
```





